[package]
name = "zfs_tune_bench"
version = "0.1.0"
authors = ["microuser <microuser@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
csv = "1.1.1"